backend:
  name: git-gateway
  branch: main
media_folder: static/imgages
public_folder: /images
slug:
  encoding: 'ascii'
  clean_accents: true
  sanitize_replacement: '_'
# Uncomment local_backend when you need to develop in your local 
local_backend: true # run npx netlify-cms-proxy-server for local testing
collections:
  - name: 'pages'
    description: 'Sivujen asetukset'
    label: 'Sivut'
    editor:
     preview: false
    files:
      - label: 'Home'
        name: 'home'
        file: 'content/home.json'
        preview_path: index
        fields:
        - label: "Hero"
          comment: "Heroon voi laittaa yhden suuren otsikon, jonka maksimimitta on 50-kirjainta. Pääotsikon alle voidaan liittää vapaamuotoinen alaotsikko. Yleisesti Kuva täyttää puolet lohkon koon, mutta halutessasi voit leventää kuvan ottamaan 100% lohkosta. Heron saa asettaa joko vasemmalle tai oikealle puolelle. Voit myös kuvan sijaan liittää .gif liikkuvan-kuvan tai YouTube-videon. Lohkon päätyyn pystyt lisäämään maksimissaan 2 toimintakehotetta."
          name: "Hero"
          widget: object
          fields:
            - { label: "Otsikko", name: "Title", widget: "string", max: 50, required: false}
            - { label: "Alaotsikko", name: "Subtitle", widget: "string", required: false}
            - { label: "Aseta sisältö", name: "Align", widget: "select", options: ["left", "right"] required: false}
            - label: "Media"
              name: "media"
              widget: "select"
              options:
                - { label: "Kuva", value: "image" }
                - { label: "Video", value: "video" }
            filter: { field: "media", value: "image"}
                - { label: "Kuva", name: "Image", widget: "image", required: false}
            filter: { field: "media", value: "video"}
                 - { label: "Video, name: "url", widget: "string", required: false}
      - label: 'About'
        name: 'about'
        file: 'content/about.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Publish Date', name: 'date', widget: 'datetime' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
          
  - label: 'Blog'
    name: 'blog'
    folder: 'content/blogPosts'
    create: true
    slug: '{{year}}-{{month}}-{{day}}_{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - {
          label: 'Publish Date',
          name: 'date',
          widget: 'datetime',
          required: true,
        }
      - {
          label: 'Featured Image',
          name: 'thumbnail',
          widget: 'image',
          required: true,
        }
      - { label: 'Body', name: 'body', widget: 'markdown', required: true }
